### ISSUE TITLE
Needs update to 23.08 and vkBasalt version 0.3.2.10

### ISSUE THREAD

**Issue by Eckoa** [flathub/org.freedesktop.Platform.VulkanLayer.vkBasalt#15]
Steam just updated to runtime 23.08 this being still on 22.08 means it isnt working anymore unless you downgrade steam. vkBasalt also had an update at the beginning of july which while really just a GCC fix im not sure there is a reason not to update this also.

**Comment by TheEvilSkeleton** [comment]
Right, thanks for reminding me!
