### ISSUE TITLE
Bottles requesting version 24.08

### ISSUE THREAD

**Issue by Plyply99** [flathub/org.freedesktop.Platform.VulkanLayer.vkBasalt#19]
![Screenshot from 2024-10-13 19-07-20](https://github.com/user-attachments/assets/9a237c7d-dba0-4286-b76a-b2a1c6163c70)

Searched on Flathub and highest version is 23.08.

`Similar refs found for ‘org.freedesktop.Platform.VulkanLayer.vkBasalt’ in remote ‘flathub’ (system):

   1) runtime/org.freedesktop.Platform.VulkanLayer.vkBasalt/x86_64/21.08
   2) runtime/org.freedesktop.Platform.VulkanLayer.vkBasalt/x86_64/22.08
   3) runtime/org.freedesktop.Platform.VulkanLayer.vkBasalt/x86_64/23.08
   4) runtime/org.freedesktop.Platform.VulkanLayer.vkBasalt/x86_64/stable
`

Thanks!

**Comment by TheEvilSkeleton** [comment]
Whoops, I had completely forgotten to bump the version. Thanks for reminding me :)

It should now be available at `runtime/org.freedesktop.Platform.VulkanLayer.vkBasalt/x86_64/24.08`
